version: '3.8'

services:
  backend:
    build:
      context: ./backend_go
      dockerfile: Dockerfile
    container_name: chinese_learning_backend
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - GIN_MODE=release
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    volumes:
      - ./backend_go/db:/app/db
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend_react
      dockerfile: Dockerfile
    container_name: chinese_learning_frontend
    ports:
      - '${FRONTEND_PORT}:80'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
