version: "3.8"

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "${LLM_ENDPOINT_PORT:-8008}:11434"
    environment:
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - LLM_MODEL_ID=${LLM_MODEL_ID:-"llama3.2:1b"}
    volumes:
      - models:/root/.cache/ollama

  my-app:
    container_name: my-app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ollama-server
    environment:
      - OLLAMA_SERVER_HOST=ollama-server
      - OLLAMA_SERVER_PORT=11434
    command: uvicorn app:app --host 0.0.0.0 --port 8000

networks:
  default:
    driver: bridge

volumes:
  models:
